#!/usr/bin/env python3
"""The office wall, redrawn on the 8px grid: four tiles on one 32x8 sheet.

FOUR is the whole tileset, not a subset of one. The world's brickwork is not
painted by hand anywhere -- every tile in all 24 rooms is generated by four
auto-layer rules on the `brick` IntGrid value, and those rules only ever ask for
fill, top edge, left edge, and top-left corner. So the grid change needs exactly
these four, and a bigger sheet would be four tiles plus decoration nothing
places.

Order on the sheet IS the tile id the rules use, so do not reorder:

    0  fill        2  left edge
    1  top edge    3  top-left corner

Colours are sampled from the 16px art this replaces (Brick_and_Stone.png tiles
10/13/33/83), so the wall reads as the same wall at a finer grain rather than as
a different building. The trim keeps its three-band structure -- highlight, body,
shadow line -- because that is what makes it read as a stone lip over brick
instead of a grey border; it is just 3px deep now instead of 5.

The fill is a running bond with a half-brick offset per course, which tiles
seamlessly in both axes: courses are 4px, bricks are 8px, so an 8px tile holds
exactly two courses and the offset returns to 0 every second tile.

Re-run after editing: python3 tools/gen_bricks_8px.py
"""
import os
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "ldtk", "art")
CELL = 8

# Sampled straight off the 16px sheet.
STONE_HI = (0x79, 0x79, 0x79, 255)
STONE = (0x59, 0x59, 0x59, 255)
STONE_DARK = (0x2E, 0x2E, 0x2E, 255)
MORTAR = (0x40, 0x11, 0x0C, 255)
# Brick faces, lit top to bottom. Two tones per course so a 4px brick still has
# a lip on it -- flat 4px bricks read as stripes.
FACE_HI = (0x84, 0x23, 0x18, 255)
FACE = (0x69, 0x1C, 0x13, 255)
FACE_LO = (0x55, 0x17, 0x10, 255)
# Every second brick along a course is a shade off, so a long wall does not
# stripe. Keyed off the brick's x index, not random: a re-run has to give the
# same sheet or the whole world's walls shuffle.
FACE_ALT = (0x5F, 0x19, 0x11, 255)

TRIM = 3          # highlight + body + shadow line
BRICK_W = 8
COURSE_H = 4


def brick_px(x, y):
    """One pixel of the running-bond fill, in TILE coordinates."""
    course = y // COURSE_H
    row_in = y % COURSE_H
    if row_in == COURSE_H - 1:
        return MORTAR                      # horizontal joint
    offset = 0 if course % 2 == 0 else BRICK_W // 2
    if (x - offset) % BRICK_W == 0:
        return MORTAR                      # vertical joint
    index = (x - offset) // BRICK_W
    base = FACE if index % 2 == 0 else FACE_ALT
    if row_in == 0:
        return FACE_HI                     # top lip catches the light
    if row_in == COURSE_H - 2:
        return FACE_LO
    return base


def draw(top, left):
    """One tile: brick fill, with a stone lip on the requested sides."""
    img = Image.new("RGBA", (CELL, CELL), (0, 0, 0, 0))
    px = img.load()
    for y in range(CELL):
        for x in range(CELL):
            px[x, y] = brick_px(x, y)
    if top:
        for x in range(CELL):
            px[x, 0] = STONE_HI
            px[x, 1] = STONE
            px[x, 2] = STONE_DARK
    if left:
        for y in range(CELL):
            px[0, y] = STONE_HI
            px[1, y] = STONE
            px[2, y] = STONE_DARK
    if top and left:
        # The corner belongs to the top run, so the lip reads as one piece
        # turning rather than as two strips meeting in a seam.
        px[0, 0] = STONE_HI
        px[1, 0] = STONE_HI
        px[2, 0] = STONE_HI
        px[0, 1] = STONE_HI
        px[1, 1] = STONE
        px[2, 1] = STONE
        px[0, 2] = STONE_HI
        px[1, 2] = STONE
        px[2, 2] = STONE_DARK
    return img


TILES = [
    ("fill", False, False),
    ("top", True, False),
    ("left", False, True),
    ("corner", True, True),
]

sheet = Image.new("RGBA", (CELL * len(TILES), CELL), (0, 0, 0, 0))
for i, (_name, top, left) in enumerate(TILES):
    sheet.paste(draw(top, left), (i * CELL, 0))

os.makedirs(OUT, exist_ok=True)
path = os.path.join(OUT, "bricks_8px.png")
sheet.save(path)
print("wrote %s  %dx%d  (%s)"
      % (path, sheet.width, sheet.height, ", ".join(t[0] for t in TILES)))
