#!/usr/bin/env python3
"""The Collisions layer's tileset: the office wall, plus the ceiling you stand on.

FOUR is the whole tileset, not a subset of one. The world's brickwork is not
painted by hand anywhere -- every tile in all 24 rooms is generated by four
auto-layer rules on the `brick` IntGrid value, and those rules only ever ask for
fill, top edge, left edge, and top-left corner. So the grid change needs exactly
these four, and a bigger sheet would be four tiles plus decoration nothing
places.

Order on the sheet IS the tile id the rules use, so do not reorder:

    0  fill        2  left edge      4  ceiling floor
    1  top edge    3  top-left corner 5  ceiling floor + panel

THE CEILING TILES LIVE ON THE BRICK SHEET because an LDtk auto-layer has exactly
ONE tileset, and both are painted on `Collisions`. They are drawn from
tools/gen_ceiling_panel.py's palette rather than from their own copy of it, so
the ceiling you paint and the ceiling props cannot drift apart.

Painted, not placed: 4 and 5 are what the `ceiling_flor` IntGrid value lays down,
so a run of suspended ceiling is brushed in like a wall and is solid for the same
reason every other tile here is (scripts/ldtk_tileset_post_import.gd gives every
tile in the sheet a full square).

Colours are sampled from the 16px art this replaces (Brick_and_Stone.png tiles
10/13/33/83), so the wall reads as the same wall at a finer grain rather than as
a different building. The trim keeps its three-band structure -- highlight, body,
shadow line -- because that is what makes it read as a stone lip over brick
instead of a grey border; it is just 3px deep now instead of 5.

The fill is a running bond with a half-brick offset per course, which tiles
seamlessly in both axes: courses are 4px, bricks are 8px, so an 8px tile holds
exactly two courses and the offset returns to 0 every second tile.

Re-run after editing: python3 tools/gen_bricks_8px.py
"""
import os
import sys

from PIL import Image

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_ceiling_panel import (FIELD_HI, FIELD_LO, FRAME, LIP_HI, LIP_LO,
                               RAIL_HI, TILE_EDGE, TILE_HI, TILE_LO,
                               mix, shade, speckle)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "ldtk", "art")
CELL = 8

# Sampled straight off the 16px sheet.
STONE_HI = (0x79, 0x79, 0x79, 255)
STONE = (0x59, 0x59, 0x59, 255)
STONE_DARK = (0x2E, 0x2E, 0x2E, 255)
MORTAR = (0x40, 0x11, 0x0C, 255)
# Brick faces, lit top to bottom. Two tones per course so a 4px brick still has
# a lip on it -- flat 4px bricks read as stripes.
FACE_HI = (0x84, 0x23, 0x18, 255)
FACE = (0x69, 0x1C, 0x13, 255)
FACE_LO = (0x55, 0x17, 0x10, 255)
# Every second brick along a course is a shade off, so a long wall does not
# stripe. Keyed off the brick's x index, not random: a re-run has to give the
# same sheet or the whole world's walls shuffle.
FACE_ALT = (0x5F, 0x19, 0x11, 255)

TRIM = 3          # highlight + body + shadow line
BRICK_W = 8
COURSE_H = 4


def brick_px(x, y):
    """One pixel of the running-bond fill, in TILE coordinates."""
    course = y // COURSE_H
    row_in = y % COURSE_H
    if row_in == COURSE_H - 1:
        return MORTAR                      # horizontal joint
    offset = 0 if course % 2 == 0 else BRICK_W // 2
    if (x - offset) % BRICK_W == 0:
        return MORTAR                      # vertical joint
    index = (x - offset) // BRICK_W
    base = FACE if index % 2 == 0 else FACE_ALT
    if row_in == 0:
        return FACE_HI                     # top lip catches the light
    if row_in == COURSE_H - 2:
        return FACE_LO
    return base


def draw(top, left):
    """One tile: brick fill, with a stone lip on the requested sides."""
    img = Image.new("RGBA", (CELL, CELL), (0, 0, 0, 0))
    px = img.load()
    for y in range(CELL):
        for x in range(CELL):
            px[x, y] = brick_px(x, y)
    if top:
        for x in range(CELL):
            px[x, 0] = STONE_HI
            px[x, 1] = STONE
            px[x, 2] = STONE_DARK
    if left:
        for y in range(CELL):
            px[0, y] = STONE_HI
            px[1, y] = STONE
            px[2, y] = STONE_DARK
    if top and left:
        # The corner belongs to the top run, so the lip reads as one piece
        # turning rather than as two strips meeting in a seam.
        px[0, 0] = STONE_HI
        px[1, 0] = STONE_HI
        px[2, 0] = STONE_HI
        px[0, 1] = STONE_HI
        px[1, 1] = STONE
        px[2, 1] = STONE
        px[0, 2] = STONE_HI
        px[1, 2] = STONE
        px[2, 2] = STONE_DARK
    return img


def ceiling(panel):
    """One 8px cell of suspended office ceiling, seen EDGE ON as a surface.

    The lip is the brightest thing on the cell because it is what says "stand
    here" — gen_platforms.py records what a dark top row reads as instead, which
    is a hole. The T-bar seam runs down the left edge only, so a painted run
    comes out as a grid rather than as one long board, and it stops at the lip
    because a T-bar does not cross the top surface.

    `panel` puts an UNLIT light panel in the underside. Unlit is not a
    compromise, it is the only honest option: CanvasModulate is 0.05 and
    multiplies every CanvasItem, so a painted luminous panel arrives at 5% of
    what was drawn. Paint gives you the architecture; a CeilingPanel dropped on
    top of it is what makes one glow (see LIGHTING.md).
    """
    img = Image.new("RGBA", (CELL, CELL), (0, 0, 0, 0))
    px = img.load()
    for x in range(CELL):
        px[x, 0] = shade(LIP_HI, speckle(x, 0)) + (255,)
        px[x, 1] = shade(LIP_LO, speckle(x, 1)) + (255,)
        for y in range(2, CELL - 1):
            t = 1.0 - (y - 2) / float(CELL - 3)
            px[x, y] = shade(mix(TILE_LO, TILE_HI, 0.15 + t * 0.7),
                             speckle(x, y)) + (255,)
        px[x, CELL - 1] = TILE_EDGE + (255,)
    for y in range(2, CELL):
        px[0, y] = shade(RAIL_HI, -20) + (255,)
    if panel:
        for x in range(2, CELL - 1):
            for y in range(4, CELL - 1):
                px[x, y] = FRAME + (255,) if x in (2, CELL - 2) or y == 4 \
                    else mix(FIELD_LO, FIELD_HI, 0.7) + (255,)
    return img


TILES = [
    ("fill", False, False),
    ("top", True, False),
    ("left", False, True),
    ("corner", True, True),
]
CEILING = [("ceiling", False), ("ceiling panel", True)]

sheet = Image.new("RGBA", (CELL * (len(TILES) + len(CEILING)), CELL), (0, 0, 0, 0))
for i, (_name, top, left) in enumerate(TILES):
    sheet.paste(draw(top, left), (i * CELL, 0))
for i, (_name, panel) in enumerate(CEILING):
    sheet.paste(ceiling(panel), ((len(TILES) + i) * CELL, 0))

os.makedirs(OUT, exist_ok=True)
path = os.path.join(OUT, "bricks_8px.png")
sheet.save(path)
print("wrote %s  %dx%d  (%s)"
      % (path, sheet.width, sheet.height,
         ", ".join([t[0] for t in TILES] + [c[0] for c in CEILING])))
