"""Crisp native-size garden ornament, ramps from the garden PixelLab swatch.
No resized source art: silhouette, mosaic and botanical linework are drawn
at native resolution, matching Act 2's pulled-back watercolor convention.
"""
from pathlib import Path
from collections import Counter
from PIL import Image,ImageDraw
import colorsys
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'assets/props/sky_gardens'
src=OUT/'source/garden_swatch.png'
colors=Counter(Image.open(src).convert('RGB').getdata())
def ramp(lo,hi):
 a=[c for c,n in colors.most_common() if lo<colorsys.rgb_to_hsv(*(v/255 for v in c))[0]<hi and colorsys.rgb_to_hsv(*(v/255 for v in c))[1]>.25]
 a=sorted(a[:100],key=lambda c:sum(c));return [a[round((len(a)-1)*t)]+(255,) for t in [0,.25,.5,.75,1]]
gold=ramp(.07,.18);teal=ramp(.42,.65);rose=ramp(.0,.07)
im=Image.new('RGBA',(192,96));d=ImageDraw.Draw(im)
# Pavilion, recessed empty arch so the sky remains visible.
for inset in range(5):
 d.line([(8+inset,88),(8+inset,36),(24,16+inset),(32,8+inset),(40,16+inset),(56-inset,36),(56-inset,88)],fill=gold[min(inset,4)],width=1)
for x in (8,52):
 d.rectangle((x,38,x+4,87),fill=gold[2]);d.line((x,38,x,87),fill=gold[4])
 for y in range(40,84,8):d.rectangle((x+1,y,x+3,y+3),fill=teal[2])
d.rectangle((4,88,60,91),fill=gold[2]);d.line((4,88,60,88),fill=gold[4])
# A cypress with layered one-pixel edges; subdued at runtime in background.
for y in range(12,88):
 half=min(13,int((y-12)*.22));x=84
 d.line((x-half,y,x+half,y),fill=teal[1 if y%3 else 2])
 d.point((x-half,y),fill=teal[3])
d.rectangle((82,86,85,95),fill=gold[1])
# Planters with small blossoms. Sprites are non-solid foreground details.
for k in range(3):
 x=104+k*24
 d.polygon([(x,81),(x+13,81),(x+11,93),(x+2,93)],fill=teal[2])
 d.line((x,81,x+13,81),fill=gold[4],width=2)
 d.line((x+2,84,x+3,90),fill=teal[4]);d.line((x+11,83,x+10,91),fill=teal[0])
 d.line((x+4,85,x+9,85),fill=gold[2]);d.point((x+6,88),fill=gold[3])
 for j in range(3):
  xx=x+3+j*4;yy=72+(j+k)%3*3
  d.line((xx,yy,xx,80),fill=teal[1]);d.rectangle((xx-1,yy-1,xx+1,yy+1),fill=rose[3]);d.point((xx,yy),fill=gold[4])
# Tasseled checkpoint pennant, same palette as the rideable rug.
d.line((176,66,176,94),fill=gold[3]);d.polygon([(177,67),(189,67),(185,72),(189,76),(177,76)],fill=teal[2]);d.line((178,68,186,68),fill=gold[4]);d.point((181,71),fill=gold[4]);d.line((175,94,179,94),fill=gold[1])
im.save(OUT/'ornaments.png')
(OUT/'README.md').write_text('Native pixel geometry generated by tools/gen_sky_garden_decor.py. Palette source: PixelLab garden swatch source/garden_swatch.png (job 284d2c18-e630-4b09-9116-8f7620fae864, seed 47). The source supplies color ramps only; native shapes are procedural, never downsampled. Decorative arches, cypress and pots have no collision.\n')
