#!/usr/bin/env python3
"""One-shot migration: move the LDtk world from a 16px grid to an 8px grid.

WHAT MOVES AND WHAT DOES NOT. Nothing moves in PIXELS. Rooms stay 320x192,
entities stay exactly where they are, collision covers exactly the same space,
and the character is untouched. What changes is the resolution the world is
AUTHORED at: every 16px cell becomes a 2x2 block of 8px cells, so a room goes
from 20x12 cells to 40x24 and new geometry can be placed on a half-cell.

That works because the world holds almost no hand-placed data. There are zero
hand-painted tiles in all 24 rooms -- every one of the 1893 tiles on screen is
generated by four auto-layer rules on the `brick` IntGrid value. So the only
authored things are two IntGrid layers and 320 entities, and both convert
mechanically.

THE AUTO-LAYER TILES ARE REGENERATED HERE, not by LDtk. They are stored in the
.ldtk and the Godot importer reads them straight out of it, so a converted file
with stale tiles would import a world painted for the old grid. The rule
evaluator below was checked against LDtk's own output first: run with --verify
and it repaints the CURRENT 16px world from the rules and diffs it against the
stored tiles. That came back byte-identical on all 1893 tiles across all 24
levels, which is the only reason it is trusted to paint the 8px one.

Two details of LDtk's evaluator that are not guessable and were found that way:
`outOfBoundsValue` is 2, so past the edge of a room counts AS brick (a wall
along the room border draws no lip), and every rule also matches its X-, Y- and
XY-mirrored self, emitting the flip bits in the tile's `f` field. Miss either
and the walls come out inside-out.

The brick art moves with the grid: tools/gen_bricks_8px.py draws the four tiles
the rules actually ask for, and tileset 32 is repointed at them.

LDtk MUST BE CLOSED. It holds the project in memory and writes it back whole
(CLAUDE.md), so a scripted edit under a running LDtk is reverted silently.

Usage:  python3 tools/ldtk_to_8px.py --verify   # check the evaluator, write nothing
        python3 tools/ldtk_to_8px.py            # dry run: report the conversion
        python3 tools/ldtk_to_8px.py --apply
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LDTK = os.path.join(ROOT, "ldtk", "hooshang_act1.ldtk")
OLD, NEW = 16, 8

BRICK_TILESET_UID = 32
NEW_TILESET = {
    "relPath": "art/bricks_8px.png",
    "identifier": "Bricks8px",
    "pxWid": 32, "pxHei": 8,
    "__cWid": 4, "__cHei": 1,
    "tileGridSize": NEW,
}
# Old 16px tile id -> new 8px tile id, in tools/gen_bricks_8px.py's sheet order.
TILE_REMAP = {10: 0, 33: 1, 83: 2, 13: 3}

APPLY = "--apply" in sys.argv
VERIFY = "--verify" in sys.argv


# ------------------------------------------------------- LDtk's auto-layer ----

def _variants(rule):
    """(flip_bits, pattern) for each mirror the rule is allowed to match in.

    Order matters and is LDtk's: unmirrored, X, Y, XY. It decides which rule
    wins where two orientations both match, and any other order disagrees with
    the stored world."""
    n, p = rule["size"], rule["pattern"]
    combos = [(0, 0)]
    if rule["flipX"]:
        combos.append((1, 0))
    if rule["flipY"]:
        combos.append((0, 1))
    if rule["flipX"] and rule["flipY"]:
        combos.append((1, 1))
    out = []
    for fx, fy in combos:
        pat = []
        for y in range(n):
            for x in range(n):
                sx = n - 1 - x if fx else x
                sy = n - 1 - y if fy else y
                pat.append(p[sy * n + sx])
        out.append((fx | (fy << 1), pat))
    return out


def paint(rules, csv, w, h, oob):
    """Run the rules over an IntGrid. Returns {coordId: (ruleUid, tileId, flip)}."""
    def val(x, y):
        return csv[y * w + x] if (0 <= x < w and 0 <= y < h) else oob

    out = {}
    for y in range(h):
        for x in range(w):
            if csv[y * w + x] != 2:
                continue
            hit = None
            for rule in rules:
                n = rule["size"]
                rad = n // 2
                for flip, pat in _variants(rule):
                    ok = True
                    for py in range(n):
                        for px in range(n):
                            want = pat[py * n + px]
                            if want == 0:
                                continue
                            got = val(x + px - rad, y + py - rad)
                            if (want > 0 and got != want) or (want < 0 and got == -want):
                                ok = False
                                break
                        if not ok:
                            break
                    if ok:
                        hit = (rule["uid"], rule["tileRectsIds"][0][0], flip)
                        break
                if hit:
                    break
            if hit:
                out[y * w + x] = hit
    return out


def _rules(d):
    layer = [l for l in d["defs"]["layers"] if l["identifier"] == "Collisions"][0]
    rules = [r for g in layer["autoRuleGroups"] for r in g["rules"] if r["active"]]
    return layer, rules


def verify(d):
    """Repaint the CURRENT world from the rules and diff against what LDtk stored."""
    _layer, rules = _rules(d)
    oob = rules[0]["outOfBoundsValue"]
    bad = total = 0
    for lv in d["levels"]:
        li = _collisions(lv)
        mine = paint(rules, li["intGridCsv"], li["__cWid"], li["__cHei"], oob)
        theirs = {t["d"][1]: (t["d"][0], t["t"], t["f"]) for t in li["autoLayerTiles"]}
        total += len(theirs)
        bad += len(set(mine.items()) ^ set(theirs.items()))
    print("verify: %d mismatches against %d stored tiles across %d levels"
          % (bad, total, len(d["levels"])))
    return bad == 0


def _collisions(level):
    return [x for x in level["layerInstances"] if x["__identifier"] == "Collisions"][0]


# ------------------------------------------------------------- conversion ----

def double(csv, w, h):
    """Each cell becomes a 2x2 block, so the shape is identical in pixels."""
    out = []
    for y in range(h):
        for _ in range(2):
            for x in range(w):
                v = csv[y * w + x]
                out.append(v)
                out.append(v)
    return out


def convert(d):
    layer_def, rules = _rules(d)
    oob = rules[0]["outOfBoundsValue"]

    for l in d["defs"]["layers"]:
        l["gridSize"] = NEW
    for r in rules:
        old = r["tileRectsIds"][0][0]
        r["tileRectsIds"] = [[TILE_REMAP[old]]]

    ts = [t for t in d["defs"]["tilesets"] if t["uid"] == BRICK_TILESET_UID][0]
    ts.update(NEW_TILESET)
    # LDtk caches per-tile opacity/average colour off the OLD art. Cleared so it
    # recomputes rather than rendering the new sheet through the old cache.
    ts["cachedPixelData"] = None

    stats = {"levels": 0, "tiles": 0, "entities": 0}
    for lv in d["levels"]:
        stats["levels"] += 1
        for li in lv["layerInstances"]:
            w, h = li["__cWid"], li["__cHei"]
            li["__gridSize"] = NEW
            li["__cWid"], li["__cHei"] = w * 2, h * 2
            if li["intGridCsv"]:
                li["intGridCsv"] = double(li["intGridCsv"], w, h)
            if li["__tilesetDefUid"] == BRICK_TILESET_UID:
                li["__tilesetRelPath"] = NEW_TILESET["relPath"]
            for e in li["entityInstances"]:
                # Recomputed from px, NOT doubled: an entity at x=184 sat in cell
                # 11 on the old grid and sits in cell 23 on the new one, and
                # 11*2 = 22 would quietly walk it a cell to the left.
                e["__grid"] = [e["px"][0] // NEW, e["px"][1] // NEW]
                stats["entities"] += 1
            li["autoLayerTiles"] = []

        li = _collisions(lv)
        painted = paint(rules, li["intGridCsv"], li["__cWid"], li["__cHei"], oob)
        cw = NEW_TILESET["__cWid"]
        tiles = []
        for coord, (rule_uid, tile, flip) in sorted(painted.items()):
            cx, cy = coord % li["__cWid"], coord // li["__cWid"]
            tiles.append({
                "px": [cx * NEW, cy * NEW],
                "src": [(tile % cw) * NEW, (tile // cw) * NEW],
                "f": flip, "t": tile, "d": [rule_uid, coord], "a": 1,
            })
        li["autoLayerTiles"] = tiles
        stats["tiles"] += len(tiles)
    return stats


def main():
    d = json.load(open(LDTK))
    if VERIFY:
        sys.exit(0 if verify(d) else 1)

    before = sum(len(li["autoLayerTiles"]) for lv in d["levels"]
                 for li in lv["layerInstances"])
    sizes = {(lv["identifier"], _collisions(lv)["__cWid"], _collisions(lv)["__cHei"])
             for lv in d["levels"]}
    print("before: grid %dpx, %d auto tiles, rooms e.g. %s"
          % (OLD, before, sorted(sizes)[0][1:]))

    if not verify(d):
        raise SystemExit("!! the rule evaluator disagrees with the stored world "
                         "-- refusing to repaint it")

    stats = convert(d)
    print("after : grid %dpx, %d auto tiles, %d entities re-gridded, %d levels"
          % (NEW, stats["tiles"], stats["entities"], stats["levels"]))
    if APPLY:
        tmp = LDTK + ".tmp"
        with open(tmp, "w") as f:
            json.dump(d, f, indent="\t")
        os.replace(tmp, LDTK)
        print("APPLIED to %s" % LDTK)
    else:
        print("DRY RUN -- nothing written. Re-run with --apply")


main()
